apiVersion: v1
kind: Pod
metadata:
  name: webservice01
spec:
  containers:
  - name: webby
    image: reg.alta3.com/5268-sharma-webby02
    ports:
    - name: web
      containerPort: 8888
      protocol: TCP
